language: java

jdk:
- oraclejdk8

sudo: false

branches:
  only:
    - master

after_success:
  - "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings settings.xml -DskipTests=true -B || mvn clean verify"

env:
  global:
  - secure: aVtXHB4eKckr4tVPph49/7JnvCqaMmbPDUpUrRfFRWivmBzBuiB7TeAGWq6ih38C72OrCbn5F4szg22eOjBUVofemVl+aTOj+fiV4RG8E2B6LKV0tnOkrzFJM8sFTqBan9TpxBafbh3lBFNVeOi6Qj4bReAWwFHovxusxMSn4BsOfj7xp4Wh3lCC7gW4m5uhiOZzuDD9RoVOSagWtww2OLbH6w3WVNG4xv1xqCUF3i0ZtaFptP5MAJJzBf9VzBqpfDRRXV+gSSAoNNVAsJxTiwcO2GTDu5SOKO525uRq9umsFeDCoBEWE2Y7u1xNGzcYkTQkoCb1oB3UdXcfKsslj+E2ThWQCAojdVLKx4pNRzf/GpBhx25bpmOmzzwD1mrUVDwvlaDdGRE53jP5bdv3sIm5hTXyFk4x1+vx3JP55H+zVMsqqqNecBtQSlsxXP81VY2dFn6CzoAvBZROAKmaEwzh67WENJCQNewOWns9+XIXxExj6xXNWj7ERLP6L44rJjBhKUf8nfS1QUhYzcC/nGd0/knilqzht89WAPDC8dyDFYkmBRDiQLJ8YDK71r0FmlhhjU+uK9R4UdGA4XnIFHF/BPG9nMk2jCpHwqBuTXBvb9CIrKMvyUShOXkd5xDM6xgy/q8cuFgzK7Ygtm0Iv6fXcPaYUFUWBj5zEuDyBhY=
  - secure: Jkd7CH+Tar0+JhLXgFDSti6J6DuQfB8tPYPF1p8ZKc3fSRGUpqxHJ3Xp6zPImIc8zm+9leZz/0T04Y+ZGfurAgXbwLM0v8S7biU6vRlaW9ClPktmswh/JeHe06mBzcKUp+oxqRg+48Xd+6yfYWaWy/U75QltIq+4tlNtB6QCvbY23FeAdbm7f470khSEmcADCzU76KrzWFJ7d7lrcWWbwwmdEMmZH1uxhKpFEe2K2zFn4YOPblwB3J8TJdnoJk3pxK110Fh1T644M8Pz13hxsHEeCdFLWiNf649j/VQu42THMw9u5+PGTGCQpOSc0ATtfGHey/fKG3CpZvqi3zo8ZXphszXl+OUERICciirG9OiAKjy+is/lQbTm3KeWRDuRKlHh374WMjEml87m20KEldmH5qG48LTEdRdvtcXdMczb94OJDBX+tAikrEdgEyfl1j1EydRtprB6K0Z3TS+tdjB6nE/AegMhFU0QR1pdxZNA/gdHKyaEo2LvHrTnPrbCuD9RC7BJbPEAaN1pTbcssNnRDx2yuw9x68cxnf07aDCBqhhCOX1qCpq5yrnMh/CfESy04UgceVzk2KGSrd7nHDlEQaWEuXp01cyFBCD0jtFgHKQghAbkGdY4ViqW/RoFkYMdDhx8nS0+CP1gmRkklTqReL/9ehmZkNHGXWQckn0=
